title: Christian Kissig
email: christian+dev-github@kissig.org
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://christiankissig.github.io"

github_username:  christiankissig

markdown: kramdown
theme: minima
